package com.bikeweb.entity;
// Generated Mar 5, 2017 10:44:25 AM by Hibernate Tools 4.3.1

import java.util.Base64;




/**
 * Bike generated by hbm2java
 */
public class Bike  implements java.io.Serializable {


     private int bikeId;
     private String bikeName;
     private Integer price;
     private String description;
     private String brand;
     private String color;
     private byte[] images;
     
     private String imageBase64;

    public Bike() {
    }

	
    public Bike(int bikeId) {
        this.bikeId = bikeId;
    }
    public Bike(int bikeId, String bikeName, Integer price, String description, String brand, String color, byte[] images) {
       this.bikeId = bikeId;
       this.bikeName = bikeName;
       this.price = price;
       this.description = description;
       this.brand = brand;
       this.color = color;
       this.images = images;
    }
   
    public int getBikeId() {
        return this.bikeId;
    }
    
    public void setBikeId(int bikeId) {
        this.bikeId = bikeId;
    }
    public String getBikeName() {
        return this.bikeName;
    }
    
    public void setBikeName(String bikeName) {
        this.bikeName = bikeName;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public byte[] getImages() {
        return this.images;
    }
    
    public void setImages(byte[] images) {
        this.images = images;
    }

    public String getImageBase64() {
        return new String(Base64.getEncoder().encode(getImages()));
    }
}


