package com.bikeweb.entity;
// Generated Mar 19, 2017 3:06:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private Set<Bike> bikes = new HashSet<Bike>(0);

    public Category() {
    }

	
    public Category(int categoryId) {
        this.categoryId = categoryId;
    }
    public Category(int categoryId, String categoryName, Set<Bike> bikes) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.bikes = bikes;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set<Bike> getBikes() {
        return this.bikes;
    }
    
    public void setBikes(Set<Bike> bikes) {
        this.bikes = bikes;
    }




}


