package com.bikeweb.entity;
// Generated Mar 26, 2017 3:19:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private int orderDetailId;
     private Bike bike;
     private Order order;
     private BigDecimal orderDetailPrice;
     private Integer orderDetailQuantity;
     private BigDecimal orderDetailTotal;

    public OrderDetail() {
    }

	
    public OrderDetail(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public OrderDetail(int orderDetailId, Bike bike, Order order, BigDecimal orderDetailPrice, Integer orderDetailQuantity, BigDecimal orderDetailTotal) {
       this.orderDetailId = orderDetailId;
       this.bike = bike;
       this.order = order;
       this.orderDetailPrice = orderDetailPrice;
       this.orderDetailQuantity = orderDetailQuantity;
       this.orderDetailTotal = orderDetailTotal;
    }
   
    public int getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public Bike getBike() {
        return this.bike;
    }
    
    public void setBike(Bike bike) {
        this.bike = bike;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public BigDecimal getOrderDetailPrice() {
        return this.orderDetailPrice;
    }
    
    public void setOrderDetailPrice(BigDecimal orderDetailPrice) {
        this.orderDetailPrice = orderDetailPrice;
    }
    public Integer getOrderDetailQuantity() {
        return this.orderDetailQuantity;
    }
    
    public void setOrderDetailQuantity(Integer orderDetailQuantity) {
        this.orderDetailQuantity = orderDetailQuantity;
    }
    public BigDecimal getOrderDetailTotal() {
        return this.orderDetailTotal;
    }
    
    public void setOrderDetailTotal(BigDecimal orderDetailTotal) {
        this.orderDetailTotal = orderDetailTotal;
    }




}


