package com.bikeweb.entity;
// Generated Mar 26, 2017 3:19:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int orderId;
     private User user;
     private BigDecimal orderTotal;
     private Integer orderQuantity;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Order() {
    }

	
    public Order(int orderId) {
        this.orderId = orderId;
    }
    public Order(int orderId, User user, BigDecimal orderTotal, Integer orderQuantity, Set<OrderDetail> orderDetails) {
       this.orderId = orderId;
       this.user = user;
       this.orderTotal = orderTotal;
       this.orderQuantity = orderQuantity;
       this.orderDetails = orderDetails;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BigDecimal getOrderTotal() {
        return this.orderTotal;
    }
    
    public void setOrderTotal(BigDecimal orderTotal) {
        this.orderTotal = orderTotal;
    }
    public Integer getOrderQuantity() {
        return this.orderQuantity;
    }
    
    public void setOrderQuantity(Integer orderQuantity) {
        this.orderQuantity = orderQuantity;
    }
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }




}


