package com.bikeweb.entity;
// Generated Mar 19, 2017 3:06:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

    private int orderId;
    private Customer customer;
    private BigDecimal orderTotal;
    private Integer orderQuantity;
    private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Order() {
    }

    public Order(int orderId) {
        this.orderId = orderId;
    }

    public Order(int orderId, Customer customer, BigDecimal orderTotal, Integer orderQuantity, Set<OrderDetail> orderDetails) {
        this.orderId = orderId;
        this.customer = customer;
        this.orderTotal = orderTotal;
        this.orderQuantity = orderQuantity;
        this.orderDetails = orderDetails;
    }

    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public BigDecimal getOrderTotal() {
        Iterator<OrderDetail> itr = orderDetails.iterator();
        BigDecimal total = BigDecimal.ZERO;
        while (itr.hasNext()) {
           OrderDetail o = itr.next();
           total  = total.add(o.getOrderDetailTotal());
        }
        return total;
    }

    public void setOrderTotal(BigDecimal orderTotal) {

        this.orderTotal = orderTotal;
    }

    public Integer getOrderQuantity() {
        return this.orderQuantity;
    }

    public void setOrderQuantity(Integer orderQuantity) {
        this.orderQuantity = orderQuantity;
    }

    public Set<OrderDetail> getOrderDetails() {

        return this.orderDetails;
    }

    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

}
