package com.bikeweb.entity;
// Generated Mar 19, 2017 3:06:13 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String userPassword;

    public User() {
    }

	
    public User(int userId) {
        this.userId = userId;
    }
    public User(int userId, String userName, String userPassword) {
       this.userId = userId;
       this.userName = userName;
       this.userPassword = userPassword;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


